### PR TITLE
Toolbar is handled correctly on small screens

### LINKED ISSUE #384: Finish handling toolbar on small screens
This was improved with our mobile release, but still doesnt handle some situations where there are a lot of tools on the toolbar. We need to figure out the best way to handle this until we revamp our UI

### PR DESCRIPTION
**Pull request by AlexHalb**
Resolves #384 

This hides the zoom buttons (as is done on the app) on small screens and moves the palette up a row. If the screen is small enough, it also moves the mark bases and swap pairs buttons to the same row as the palette.

### CODE REVIEW

**Comment by AlexHalb** [comment]
I just realized that the toolbar doesn't add or remove the row when the screen is resized. This shouldn't be an issue, however, as the only way a mobile device can resize is by rotating.

**Comment by luxaritas** [comment]
This is still a concern for me - we should support usage on smaller browser screens (including as you resize it) as well as mobile. I think the mode has a resize handler, which probably needs to call a re-layout handler on the toolbar?

**Comment by AlexHalb** [comment]
It should just be a matter of moving the right buttons between toolbars .

**Comment by luxaritas** [comment]
Thinking a bit more about this specific resolution - thoughts about making the toolbar essentially scrollable, adding arrows to the left and right ends and a mask over the toolbar content when there isn't enough room?

**Comment by AlexHalb** [comment]
MIght not be a bad idea, I'll give it a try.

**Comment by luxaritas** [comment]
Basic functionality looks great, but there's still some issues:
- We'll need to replace the undo and redo buttons with proper separate graphics :P I'm thinking just a simple left and right facing arrow, similar to the arrow on the constraint drawer
- Tapping on the right arrow does not work, but holding it does
- The direction the toolbar is moved by the left and right arrows should be swapped
- It would be good to implement dragging the toolbar back and forth if you press and swipe as opposed to tap
- We should ensure that there is never a point in the puzzle progression where this shows up. It's not necesary, and does not look so hot :D
image

**Comment by AlexHalb** [comment]
I've discovered another bug - any menus (options, boosters, etc) will be cut off by the scroll container. They show once the layout is updated, but this causes them to push everything else to the side because their width has increased. There doesn't seem to be a great solution for this - the best I can think of (that I haven't tried yet) is allowing some elements of the layout to be 'turned off' in `HLayoutContainer` (e.g. width calculations). I think this wasn't an issue previously because the toolbar's layout didn't need to be recalculated - however, for the scroll container to be displayed properly, the layout needs to be updated whenever the window is resized.

**Comment by luxaritas** [comment]
I assume you're referring to them being masked out? I think I discussed this issue with Tim with respect to the dropdown - not specifically with scroll containers, but problems with the effective layer/z-index (and masking I guess), noting the fact that if a popup ever gets created that there's really no (or at any rate, *very* few) situations where the user wouldn't want it to just show, and show above everything else. We had talked about passing the parent to the constructor, but it seems like the route we actually went is that the popup just gets added to the root mode container instead of it's "actual" parent's container. Is it possible to do the same thing with EternaMenu?

**Comment by AlexHalb** [comment]
What I ended up doing was overriding the width of the menu and using that width instead of the normal width in `HLayoutContainer`. Then, calling `updateLayout()` whenever the menu is shown/hidden updates the height and uses the correct width. The menus work fine now - I just need to find a better way to relay the correct width to `HLayoutContainer` than misusing `name`.

**Review by everyday847 — APPROVED** [review]
OK, I don't think I could have written all this myself, but I think I basically get the new PointerCapture system. The UI still works (in my hands), and from a code quality perspective I have no immediate complaints.

I'm willing to believe this breaks some random tutorial level on mobile or something, but that's sort of a bridge we must cross later.

**Pull request merged**
