### PR TITLE
Perfected ContraFold/EternaFold

### LINKED ISSUE #394: Fix rounding errors in contrafold/eternafold
Due to the time when numbers get rounded to dekacal/mol, there are unfortunate rounding errors in contrafold/eternafold/lfe/lfc. We need to fix them for clarity.

### PR DESCRIPTION
**Pull request by everyday847**
Now NNFE sum matches energy (rounding issues). @luxaritas, this will require an engine rebuild.

resolves #394

### CODE REVIEW

**Comment by rhiju** [comment]
Boris (brourd) asked at EternaCon why NNFE energies were asymmetric depending on whether strands involve occured  5'/3' vs. 3'/5' -- @everyday847 @HWaymentSteele  can you reach out to him to get some examples?

**Comment by everyday847** [comment]
Sure.

**Comment by everyday847** [comment]
@rhiju I talked him through it; he had essentially inferred the special CF/EF behavior where BPs themselves have an energy, and stacks have an energy attributed to one 'side' of the stack. It wasn't a bug he had to report per se -- he just wanted to understand why the numbers behaved the way they did vs. what he's used to.

**Comment by rhiju** [comment]
Thanks @everyday847 ! Good sign if we're getting this kind of feedback from aficionado's. We might want to put up aforum post explaining how we're doing this decomposition so that we can point experts to it.  @HWaymentSteele might be useful to show a few 'decomposed' structures in the revised eternafold paper too,  perhaps highlighting differences with vienna/contrafold that are being figured out in forums and mentioned by Boris in puzzle jam.

**Comment by everyday847** [comment]
Resolved by #414.

**Pull request closed without merging**
