### PR TITLE
URL updates when puzzle is changed

### LINKED ISSUE #111: Sync URL with current game view via history API
Reported by JR via https://getsatisfaction.com/eternagame/topics/url-issue-qkhl4n8mxudr8

### PR DESCRIPTION
**Pull request by AlexHalb**
Resolves #111

### CODE REVIEW

**Comment by luxaritas** [comment]
I think you'll also need to not do this if we're in mobile mode (Eterna.MOBILE_APP)

**Comment by AlexHalb** [comment]
That's fixed now

**Comment by luxaritas** [comment]
Hm, just realized a situation where this will break - if you go from another mode into the pose edit mode, eg from the design browser or feedback mode (via the design sidebar), the current URL will be not the puzzle URL. We probably need to handle URL changes between modes? Possible URLs (currently, as described by our backend):
```
preg_match('/\/game\/solution\/(\d+)\/(\d+)\/(\w+)\//i', $uri, $solution_uri_match);
preg_match('/\/game\/puzzle\/(\d+)\//i', $uri, $puzzle_uri_match);
preg_match('/\/game\/browse\/(\d+)\//i', $uri, $browse_uri_match);
preg_match('/\/game\/puzzlemaker\//i', $uri, $puzzlemaker_uri_match);
preg_match('/\/game\/switchmaker\/(\d+)\//i', $uri, $switchmaker_uri_match);
preg_match('/\/game\/tuttest\/\?pid=(\d+)/i', $uri, $tuttest_uri_match);
```
(for the solution URL, the first option is the puzzle, the second is the design ID, and the last option is either copyandview or seeresult)

**Comment by luxaritas** [comment]
Wait hold up, nvm. This is only the next puzzle button. That should never ever happen

**Pull request merged**
