### PR TITLE
Linearfold update

### PR DESCRIPTION
**Pull request by everyday847**
We now work with the latest LinearFold, and our instructions suggest that it be obtained via specific detached HEAD checkout rather than just grabbing latest master.

### CODE REVIEW

**Comment by luxaritas** [comment]
Please move any necessary info about cloning into the lib README. Thanks :)

**Comment by luxaritas** [comment]
Also - did we want to add some LF tests before upgrading to make sure nothing broke?

**Comment by everyday847** [comment]
Oh, yes. I'll do that. I forgot that it isn't tested in the standard suite.

**Comment by everyday847** [comment]
Changes made.

**Comment by luxaritas** [comment]
Re: LFV/LFC having identical energies: this is because currently they both use Vienna2 energies, instead of Contrafold scores. What should theoretically differ (in some cases at least) is the actual predicted structure - did you not add tests for that?

**Comment by everyday847** [comment]
If they use the same energies the structure should be the same. I didn't know they did!

I just extended the existing tests to cover LFC/V; perhaps I'll write additional folder tests in the future, of course.

**Comment by luxaritas** [comment]
> If they use the same energies the structure should be the same
...not quite. When *providing substructure energies*, they're the same. But when determining the MFE, LFV uses Vienna2 parameters whereas LFC uses Contrafold scores.

**Comment by luxaritas** [comment]
Huh, looks like none of the tests actually validate that the structure is correct - they just verify that the folding doesn't error out

**Comment by everyday847** [comment]
I see, I hadn't understood the distinction but at least that explains that LinearFoldC is different, which, good. And, correct. I'll have to write more tests, some other time, to cover that (rather important?) feature.

**Comment by everyday847** [comment]
Are you OK to merge this now, while I work on vienna?

**Comment by luxaritas** [comment]
Already did!

**Comment by everyday847** [comment]
Weird, it wasn't showing. Hooray!

**Pull request merged**
